### ISSUE TITLE
Sign In Does Not Work Due To Safari Redirect

### ISSUE THREAD

**Issue by bermed28** [pballada/yutub#1]
The AVP app per se does not sign into your google account, when you press sign in it redirects to safari to log in and then stays on the safari app, it does not log you in on the AVP app. The way to fix it is to allow the app to open links from the domain `accounts.google.com` inside the actual app and not redirect to Safari. With this change it can share the cookies form the session and allow sign in so users can use their account while in the app.

You can edit the private function `isYouTubeRelated` inside the `WebViewCoordinator` class and add the link to the array of accepted domains

```swift
private func isYouTubeRelated(url: URL) -> Bool {
    let youtubeDomains = ["youtube.com", "youtu.be", "accounts.google.com"]
    return youtubeDomains.contains { url.host?.contains($0) == true }
}
```

That way the `webView` function works and allows sign ins directly from the app and is a WAY better UX
```swift
if isYouTubeRelated(url: url) {
    // Allow navigation within the web view
    decisionHandler(.allow)
} else {
    // Open non-YouTube or Google Accounts links in Safari
    UIApplication.shared.open(url)
    decisionHandler(.cancel)
}
```

**Comment by pballada** [comment]
Good catch!
Thanks for the detailed explanation and fix, already added it.
